In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [15]:
x = np.random.randn(20,5)*np.random.uniform(-2,2,(20,5))

In [16]:
x 

array([[2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [3.414, 1.650, -0.588, 2.078, 0.694],
       [3.729, -0.308, 2.291, 0.098, -1.602],
       [-0.258, -1.992, 0.053, 0.044, -1.127],
       [-1.675, -0.329, -0.949, -2.007, -0.087],
       [3.524, -1.483, -0.050, 1.760, 0.026],
       [-0.679, 0.574, 0.428, -0.525, -0.020],
       [0.757, 0.915, -0.262, 1.212, 0.886],
       [-1.247, 0.060, 0.933, -1.337, -0.341],
       [0.529, -1.125, -1.643, 0.460, -0.343],
       [1.271, 0.770, 0.385, 0.563, 0.480],
       [-1.054, 1.009, 2.016, -2.251, -0.478],
       [-0.690, 0.638, -0.107, 0.087, 0.459],
       [-0.048, 0.964, 0.705, 0.066, -1.118],
       [0.023, -0.074, 0.835, 0.438, 0.233],
       [0.248, 0.347, 0.490, -0.630, -0.297],
       [-0.481, -0.417, -0.177, 0.748, 0.823],
       [0.193, 0.009, -1.762, -0.148, 0.147],
       [0.176, 1.131, 2.037, 0.758, -1.523]])

In [18]:
x_df=pd.DataFrame(x, columns=['x_{}'.format(i) for i in range(5)])
print(x_df.round(3))

x_temp = x_df.copy()
x_temp['x_2']=-.05
print(x_temp)

      x_0    x_1    x_2    x_3    x_4
0   2.237  2.151 -0.744  3.011  1.367
1   2.857 -1.285  0.030  1.110  0.039
2   3.414  1.650 -0.588  2.078  0.694
3   3.729 -0.308  2.291  0.098 -1.602
4  -0.258 -1.992  0.053  0.044 -1.127
5  -1.675 -0.329 -0.949 -2.007 -0.087
6   3.524 -1.483 -0.050  1.760  0.026
7  -0.679  0.574  0.428 -0.525 -0.020
8   0.757  0.915 -0.262  1.212  0.886
9  -1.247  0.060  0.933 -1.337 -0.341
10  0.529 -1.125 -1.643  0.460 -0.343
11  1.271  0.770  0.385  0.563  0.480
12 -1.054  1.009  2.016 -2.251 -0.478
13 -0.690  0.638 -0.107  0.087  0.459
14 -0.048  0.964  0.705  0.066 -1.118
15  0.023 -0.074  0.835  0.438  0.233
16  0.248  0.347  0.490 -0.630 -0.297
17 -0.481 -0.417 -0.177  0.748  0.823
18  0.193  0.009 -1.762 -0.148  0.147
19  0.176  1.131  2.037  0.758 -1.523
         x_0       x_1   x_2       x_3       x_4
0   2.237484  2.151320 -0.05  3.011355  1.367388
1   2.856829 -1.285465 -0.05  1.110094  0.039212
2   3.414422  1.649781 -0.05  2.078326  0.694224
3   3.

In [21]:
# PDP code would look like this for x_2 

# y_pdp = np.array([])
# x_pdp = np.linspace(min(x_df['x_2']-1), max(x_df['x_2']+1), 200)
# for x_i in x_pdp:
#    y_out_array = model.predict(x_i)
#    np.append(y_pdp, y_out_array.mean())
# plt.plot(x_pdp, y_pdp)

In [30]:
mask=x[:,2]<.3

In [29]:
x[mask]

array([[2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [3.414, 1.650, -0.588, 2.078, 0.694],
       [-0.258, -1.992, 0.053, 0.044, -1.127],
       [-1.675, -0.329, -0.949, -2.007, -0.087],
       [3.524, -1.483, -0.050, 1.760, 0.026],
       [0.757, 0.915, -0.262, 1.212, 0.886],
       [0.529, -1.125, -1.643, 0.460, -0.343],
       [-0.690, 0.638, -0.107, 0.087, 0.459],
       [-0.481, -0.417, -0.177, 0.748, 0.823],
       [0.193, 0.009, -1.762, -0.148, 0.147]])

In [32]:
x[np.array([True, False, True, True, False, False, True, True, False, False, True, True,False,False,True,False,True,False,True,True])]

array([[2.237, 2.151, -0.744, 3.011, 1.367],
       [3.414, 1.650, -0.588, 2.078, 0.694],
       [3.729, -0.308, 2.291, 0.098, -1.602],
       [3.524, -1.483, -0.050, 1.760, 0.026],
       [-0.679, 0.574, 0.428, -0.525, -0.020],
       [0.529, -1.125, -1.643, 0.460, -0.343],
       [1.271, 0.770, 0.385, 0.563, 0.480],
       [-0.048, 0.964, 0.705, 0.066, -1.118],
       [0.248, 0.347, 0.490, -0.630, -0.297],
       [0.193, 0.009, -1.762, -0.148, 0.147],
       [0.176, 1.131, 2.037, 0.758, -1.523]])

In [36]:
x[(np.array([0,1,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,0,1,0]))]

array([[2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.237, 2.151, -0.744, 3.011, 1.367],
       [2.237, 2.151, -0.744, 3.011, 1.367],
       [2.857, -1.285, 0.030, 1.110, 0.039],
       [2.237, 2.151, -0.744, 3.011, 1.367]])