In [1]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

np.set_printoptions(precision=2)

####Data matrix with random entries

In [2]:
D = np.random.randint(0, 100, (5,3))
D

array([[69, 25, 59],
       [34, 67, 97],
       [17,  5, 67],
       [16, 86, 55],
       [53,  0, 73]])

####Center the data

${\bf Z} = {\bf D} - {\bf 1}.\mu$

In [3]:
mu = np.mean(D, axis=0)
ones = np.ones((5,1))
mu, ones
Z = D - ones*mu
Z

array([[ 31.2, -11.6, -11.2],
       [ -3.8,  30.4,  26.8],
       [-20.8, -31.6,  -3.2],
       [-21.8,  49.4, -15.2],
       [ 15.2, -36.6,   2.8]])

In [4]:
from sklearn.decomposition import PCA
from sklearn import preprocessing

####Find $\bf A$ in rotated frame

In [5]:
pca = PCA()
A = pca.fit_transform(Z)
A

array([[-21.51,  24.6 ,  12.87],
       [ 30.91,   8.75, -25.  ],
       [-23.2 , -30.05,  -0.51],
       [ 53.24,  -6.14,  16.58],
       [-39.43,   2.84,  -3.94]])

####Covariance Matrix
$\Sigma = \frac{1}{n}{\bf Z}^T {\bf Z}$

In [6]:
Sig = Z.T.dot(Z)/5

####Apply SVD decomposition to $\Sigma$

In [7]:
U, Lambda, UT = np.linalg.svd(Sig)

####Singular value matrix: $\bf \Lambda$. In this case, the diagonal values are eigenvalues of $\Sigma$

In [8]:
Lambda = np.diag(Lambda)
Lambda

array([[ 1269.05,     0.  ,     0.  ],
       [    0.  ,   326.07,     0.  ],
       [    0.  ,     0.  ,   216.24]])

####Basis matrix

In [9]:
U

array([[-0.33, -0.94, -0.08],
       [ 0.94, -0.32, -0.06],
       [ 0.04, -0.1 ,  0.99]])

####Decomposition of Z

In [10]:
L, Delta, RT = np.linalg.svd(Z)

####Singular value matrix: $\bf \Delta$
Note: $\bf \Delta$ is not a square matrix.

In [11]:
Delta = np.diag(Delta)
Delta

array([[ 79.66,   0.  ,   0.  ],
       [  0.  ,  40.38,   0.  ],
       [  0.  ,   0.  ,  32.88]])

####Comparision of $\Sigma$ and $\Delta$

In [12]:
print Delta**2
print " "
print 5*Lambda

[[ 6345.27     0.       0.  ]
 [    0.    1630.35     0.  ]
 [    0.       0.    1081.19]]
 
[[ 6345.27     0.       0.  ]
 [    0.    1630.35     0.  ]
 [    0.       0.    1081.19]]


####We can get $\bf A$ from $\bf R$ and $\bf Z$

In [13]:
A2 = Z.dot(RT.T)
A2

array([[-21.51,  24.6 ,  12.87],
       [ 30.91,   8.75, -25.  ],
       [-23.2 , -30.05,  -0.51],
       [ 53.24,  -6.14,  16.58],
       [-39.43,   2.84,  -3.94]])

####Same as $\bf A$

In [14]:
A

array([[-21.51,  24.6 ,  12.87],
       [ 30.91,   8.75, -25.  ],
       [-23.2 , -30.05,  -0.51],
       [ 53.24,  -6.14,  16.58],
       [-39.43,   2.84,  -3.94]])

####Also $\bf R$ and $\bf U$ are the same

In [15]:
print RT.T
print " "
print U

[[-0.33  0.94  0.08]
 [ 0.94  0.32  0.06]
 [ 0.04  0.1  -0.99]]
 
[[-0.33 -0.94 -0.08]
 [ 0.94 -0.32 -0.06]
 [ 0.04 -0.1   0.99]]
