In [2]:
import numpy as np

In [9]:
row =np.array([[1,2,3]])

In [10]:
column = np.array([[1],[2],[3]])

In [11]:
row.shape

(1, 3)

In [12]:
column.shape

(3, 1)

In [8]:
row

array([1, 2, 3])

In [18]:
np.dot(row,column)


array([[14]])

In [21]:
np.dot(column,row)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [22]:
M=np.array([[1,2],[3,4],[5,6]])

In [23]:
M

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
M.transpose()


array([[1, 3, 5],
       [2, 4, 6]])