# Assessment 3 Review


* Be able to estimate probabilities with simulations in python

* Review the A/B testing and the beta distribution
    * a good resource for the beta distribution:
https://stats.stackexchange.com/questions/47771/what-is-the-intuition-behind-beta-distribution

* Review hypothesis testing

* Review SQL

### Numpy, Pandas, Linear Regression

In [1]:
import numpy as np
import pandas as pd

In [2]:
bar = np.random.randint(50, size = (10))
baz = np.random.randint(50, size = (1, 10))

In [3]:
bar

array([33,  9, 17,  8, 48, 42, 12,  6, 39, 27])

In [4]:
bar.shape

(10,)

In [5]:
baz

array([[48,  7, 40, 45, 45, 10, 21,  6,  3,  4]])

In [6]:
baz.shape

(1, 10)

What's the difference?

"Non-dimensional" array can cause problems when trying to do operations 
You can reshape your data using `reshape`

In [7]:
bar.reshape((1,10))

array([[33,  9, 17,  8, 48, 42, 12,  6, 39, 27]])

Indexing
https://docs.scipy.org/doc/numpy/user/basics.indexing.html

Filtering with masks

A masked array is the combination of a standard numpy.ndarray and a mask. A mask is either nomask, indicating that no value of the associated array is invalid, or an array of booleans that determines for each element of the associated array whether the value is valid or not.

In [8]:
bar

array([33,  9, 17,  8, 48, 42, 12,  6, 39, 27])

In [9]:
bar[[0,1,5]]

array([33,  9, 42])

In [10]:
bar[[0,1,1, 5,1]]

array([33,  9,  9, 42,  9])

In [11]:
# generate numpy array with random values
# 10 rows
# 5 columns
foo = np.random.randint(50, size = (10,5))
foo

array([[31, 37, 22, 27, 36],
       [34, 49, 48, 17, 23],
       [20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [20, 48, 30, 43, 38],
       [ 5, 14, 27, 21, 11],
       [31, 14, 48, 10, 22],
       [34, 37, 41, 32, 31],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11]])

In [12]:
# create boolean array -- True for indexes with values that satisfy the criteria
foo < 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False,  True],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False,  True,  True, False, False]], dtype=bool)

In [13]:
(foo < 10).any(axis=0)

array([ True,  True,  True,  True,  True], dtype=bool)

Axes are defined for arrays with more than one dimension. A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1)

In [14]:
(foo < 10).any(axis=1)

array([False, False,  True,  True, False,  True, False, False,  True,  True], dtype=bool)

In [15]:
foo > 1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [16]:
(foo > 1).all(axis=0)

array([ True,  True,  True,  True,  True], dtype=bool)

In [17]:
(foo > 1).all(axis=1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

### Indexing (subsetting data)

In [18]:
foo[[1, 0, 3, 1]]

array([[34, 49, 48, 17, 23],
       [31, 37, 22, 27, 36],
       [17, 25,  9, 45,  6],
       [34, 49, 48, 17, 23]])

In [19]:
foo

array([[31, 37, 22, 27, 36],
       [34, 49, 48, 17, 23],
       [20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [20, 48, 30, 43, 38],
       [ 5, 14, 27, 21, 11],
       [31, 14, 48, 10, 22],
       [34, 37, 41, 32, 31],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11]])

In [20]:
foo[:,[1, 3, 3, 3, 1]]

array([[37, 27, 27, 27, 37],
       [49, 17, 17, 17, 49],
       [ 3, 32, 32, 32,  3],
       [25, 45, 45, 45, 25],
       [48, 43, 43, 43, 48],
       [14, 21, 21, 21, 14],
       [14, 10, 10, 10, 14],
       [37, 32, 32, 32, 37],
       [24,  3,  3,  3, 24],
       [ 7, 27, 27, 27,  7]])

In [21]:
(foo < 10).any(axis=1)


array([False, False,  True,  True, False,  True, False, False,  True,  True], dtype=bool)

In [22]:
mask = (foo < 10).any(axis=1)
mask

array([False, False,  True,  True, False,  True, False, False,  True,  True], dtype=bool)

In [23]:
foo[mask]

array([[20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [ 5, 14, 27, 21, 11],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11]])

In [24]:
foo

array([[31, 37, 22, 27, 36],
       [34, 49, 48, 17, 23],
       [20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [20, 48, 30, 43, 38],
       [ 5, 14, 27, 21, 11],
       [31, 14, 48, 10, 22],
       [34, 37, 41, 32, 31],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11]])

In [25]:
column_mask = (foo < 10).any(axis=0)

In [26]:
foo[:,column_mask]

array([[31, 37, 22, 27, 36],
       [34, 49, 48, 17, 23],
       [20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [20, 48, 30, 43, 38],
       [ 5, 14, 27, 21, 11],
       [31, 14, 48, 10, 22],
       [34, 37, 41, 32, 31],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11]])

In [27]:
foo

array([[31, 37, 22, 27, 36],
       [34, 49, 48, 17, 23],
       [20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [20, 48, 30, 43, 38],
       [ 5, 14, 27, 21, 11],
       [31, 14, 48, 10, 22],
       [34, 37, 41, 32, 31],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11]])

In [28]:
fizz = np.arange(10).reshape(10,1)
fizz

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [29]:
np.concatenate((foo, fizz), axis=1)

array([[31, 37, 22, 27, 36,  0],
       [34, 49, 48, 17, 23,  1],
       [20,  3, 42, 32, 17,  2],
       [17, 25,  9, 45,  6,  3],
       [20, 48, 30, 43, 38,  4],
       [ 5, 14, 27, 21, 11,  5],
       [31, 14, 48, 10, 22,  6],
       [34, 37, 41, 32, 31,  7],
       [21, 24, 12,  3, 14,  8],
       [20,  7,  4, 27, 11,  9]])

In [30]:
fuzz = np.arange(5).reshape(1,5)
fuzz

array([[0, 1, 2, 3, 4]])

In [31]:
foo

array([[31, 37, 22, 27, 36],
       [34, 49, 48, 17, 23],
       [20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [20, 48, 30, 43, 38],
       [ 5, 14, 27, 21, 11],
       [31, 14, 48, 10, 22],
       [34, 37, 41, 32, 31],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11]])

In [32]:
fuzz

array([[0, 1, 2, 3, 4]])

### Add rows or columns

In [33]:
np.concatenate((foo, fuzz), axis=0)

array([[31, 37, 22, 27, 36],
       [34, 49, 48, 17, 23],
       [20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [20, 48, 30, 43, 38],
       [ 5, 14, 27, 21, 11],
       [31, 14, 48, 10, 22],
       [34, 37, 41, 32, 31],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11],
       [ 0,  1,  2,  3,  4]])

In [34]:
foo

array([[31, 37, 22, 27, 36],
       [34, 49, 48, 17, 23],
       [20,  3, 42, 32, 17],
       [17, 25,  9, 45,  6],
       [20, 48, 30, 43, 38],
       [ 5, 14, 27, 21, 11],
       [31, 14, 48, 10, 22],
       [34, 37, 41, 32, 31],
       [21, 24, 12,  3, 14],
       [20,  7,  4, 27, 11]])

In [35]:
# alternative methods... just use concatenate!
np.hstack((foo,fizz))
np.column_stack((foo, fizz))

array([[31, 37, 22, 27, 36,  0],
       [34, 49, 48, 17, 23,  1],
       [20,  3, 42, 32, 17,  2],
       [17, 25,  9, 45,  6,  3],
       [20, 48, 30, 43, 38,  4],
       [ 5, 14, 27, 21, 11,  5],
       [31, 14, 48, 10, 22,  6],
       [34, 37, 41, 32, 31,  7],
       [21, 24, 12,  3, 14,  8],
       [20,  7,  4, 27, 11,  9]])

### PANDAS

In [36]:
df = pd.DataFrame(np.random.randint(10, size = (100, 5)), columns=['y', 'x1', 'x2', 'x3', 'x4'])

In [37]:
df.head()

y  x1  x2  x3  x4
0  6   9   5   5   8
1  6   3   2   2   3
2  5   3   3   0   8
3  4   7   3   3   6
4  4   6   3   7   9

In [38]:
df.groupby('x1')

In [39]:
df.groupby('x1').min()

y  x2  x3  x4
x1               
0   1   4   2   4
1   1   0   2   6
2   1   0   1   0
3   0   0   0   0
4   0   0   3   2
5   0   0   0   0
6   0   1   0   2
7   1   2   2   0
8   0   0   1   0
9   0   0   0   0

In [40]:
df.groupby('x1').max()

y  x2  x3  x4
x1               
0   9   9   9   9
1   4   5   8   9
2   9   6   9   9
3   9   9   7   9
4   7   7   9   7
5   8   9   9   9
6   9   9   8   9
7   7   9   8   7
8   6   9   9   9
9   9   9   9   9

In [41]:
df.groupby('x1').median()

y   x2   x3   x4
x1                    
0   4.0  8.0  5.0  4.0
1   2.0  3.0  4.0  7.0
2   3.0  3.5  6.5  3.0
3   5.0  3.0  4.0  6.0
4   2.0  2.5  6.5  4.0
5   5.0  4.0  2.0  6.0
6   3.0  7.0  3.0  5.0
7   5.0  7.0  5.0  4.0
8   4.0  6.0  4.0  3.0
9   6.0  5.0  2.0  6.0

In [42]:
df.groupby('x1').median()['x2']

x1
0    8.0
1    3.0
2    3.5
3    3.0
4    2.5
5    4.0
6    7.0
7    7.0
8    6.0
9    5.0
Name: x2, dtype: float64

In [43]:
df[['x1', 'x2']].groupby('x1').median()

x2
x1     
0   8.0
1   3.0
2   3.5
3   3.0
4   2.5
5   4.0
6   7.0
7   7.0
8   6.0
9   5.0

In [44]:
df[['x1', 'x2']].groupby('x1').median().sort_values('x2')

x2
x1     
4   2.5
1   3.0
3   3.0
2   3.5
5   4.0
9   5.0
8   6.0
6   7.0
7   7.0
0   8.0

In [45]:
#  This doesn't work because the groupby column became our new index!!
df[['x1', 'x2']].groupby('x1').median().sort_values('x1')

KeyError: 'x1'

In [46]:
df[['x1', 'x2']].groupby('x1').median().reset_index()

x1   x2
0   0  8.0
1   1  3.0
2   2  3.5
3   3  3.0
4   4  2.5
5   5  4.0
6   6  7.0
7   7  7.0
8   8  6.0
9   9  5.0

In [47]:
df[['x1', 'x2']].groupby('x1').median().reset_index().sort_values('x1')

x1   x2
0   0  8.0
1   1  3.0
2   2  3.5
3   3  3.0
4   4  2.5
5   5  4.0
6   6  7.0
7   7  7.0
8   8  6.0
9   9  5.0

In [48]:
df.groupby('x1').mean()

y        x2        x3        x4
x1                                        
0   4.428571  6.857143  5.714286  5.000000
1   2.250000  2.750000  4.500000  7.250000
2   4.000000  3.400000  6.000000  4.000000
3   5.076923  3.846154  3.538462  4.538462
4   2.666667  3.166667  6.166667  4.333333
5   4.000000  4.090909  3.545455  5.181818
6   3.615385  6.153846  4.076923  4.923077
7   4.444444  5.777778  5.000000  4.000000
8   3.750000  5.583333  4.500000  3.916667
9   5.000000  4.400000  3.200000  5.533333

In [49]:
df.sort_values('x1')

y  x1  x2  x3  x4
19  1   0   8   9   4
25  3   0   7   8   4
59  6   0   9   8   4
82  4   0   8   2   4
50  5   0   4   3   9
72  9   0   4   5   6
37  3   0   8   5   4
76  4   1   4   8   7
66  3   1   0   6   7
86  1   1   2   2   6
39  1   1   5   2   9
93  3   2   2   3   7
35  2   2   6   8   3
36  7   2   6   5   2
84  3   2   0   5   1
78  7   2   5   9   8
67  3   2   4   7   0
21  1   2   3   8   9
85  2   2   1   6   3
74  9   2   3   1   6
9   3   2   4   8   1
8   5   3   5   4   1
55  1   3   2   3   0
11  6   3   0   6   6
30  5   3   9   6   7
28  0   3   4   6   4
2   5   3   3   0   8
77  5   3   6   4   3
1   6   3   2   2   3
23  7   3   8   0   9
.. ..  ..  ..  ..  ..
41  5   7   8   8   2
47  5   7   2   2   6
13  7   7   8   4   2
83  3   8   9   9   0
99  5   8   9   3   3
38  5   8   7   2   4
61  2   8   3   6   2
58  5   8   8   2   3
52  6   8   3   3   5
98  4   8   8   7   3
24  0   8   0   7   3
46  4   8   5   5   9
45  1   8   4   1   1
73  4   8   7   6   6
33  6   8   4   3   8
7   1   9   4   0   7
10  5   9   6   3   0
14  2   9   2   7   7
16  8   9   6   1   9
92  6   9   8   0   1
27  5   9   0   5   4
71  8   9   2   8   8
31  7   9   5   1   5
48  9   9   6   2   3
81  7   9   0   2   9
53  0   9   3   9   9
63  2   9   9   0   2
70  7   9   4   1   6
90  2   9   6   4   5
0   6   9   5   5   8

[100 rows x 5 columns]

In [50]:
df.sort_values(['x1', 'x2'])

y  x1  x2  x3  x4
50  5   0   4   3   9
72  9   0   4   5   6
25  3   0   7   8   4
19  1   0   8   9   4
37  3   0   8   5   4
82  4   0   8   2   4
59  6   0   9   8   4
66  3   1   0   6   7
86  1   1   2   2   6
76  4   1   4   8   7
39  1   1   5   2   9
84  3   2   0   5   1
85  2   2   1   6   3
93  3   2   2   3   7
21  1   2   3   8   9
74  9   2   3   1   6
9   3   2   4   8   1
67  3   2   4   7   0
78  7   2   5   9   8
35  2   2   6   8   3
36  7   2   6   5   2
11  6   3   0   6   6
17  4   3   0   5   6
44  9   3   1   2   6
1   6   3   2   2   3
55  1   3   2   3   0
2   5   3   3   0   8
22  9   3   3   1   0
28  0   3   4   6   4
8   5   3   5   4   1
.. ..  ..  ..  ..  ..
41  5   7   8   8   2
65  4   7   9   7   6
80  3   7   9   6   7
24  0   8   0   7   3
52  6   8   3   3   5
61  2   8   3   6   2
33  6   8   4   3   8
45  1   8   4   1   1
46  4   8   5   5   9
38  5   8   7   2   4
73  4   8   7   6   6
58  5   8   8   2   3
98  4   8   8   7   3
83  3   8   9   9   0
99  5   8   9   3   3
27  5   9   0   5   4
81  7   9   0   2   9
14  2   9   2   7   7
71  8   9   2   8   8
53  0   9   3   9   9
7   1   9   4   0   7
70  7   9   4   1   6
0   6   9   5   5   8
31  7   9   5   1   5
10  5   9   6   3   0
16  8   9   6   1   9
48  9   9   6   2   3
90  2   9   6   4   5
92  6   9   8   0   1
63  2   9   9   0   2

[100 rows x 5 columns]

In [51]:
df.sort_values(['x2', 'x1'])

y  x1  x2  x3  x4
66  3   1   0   6   7
84  3   2   0   5   1
11  6   3   0   6   6
17  4   3   0   5   6
18  3   4   0   5   7
79  0   5   0   4   4
94  5   5   0   0   9
24  0   8   0   7   3
27  5   9   0   5   4
81  7   9   0   2   9
85  2   2   1   6   3
44  9   3   1   2   6
32  2   4   1   7   6
95  0   4   1   3   3
89  1   5   1   8   7
97  5   6   1   3   5
86  1   1   2   2   6
93  3   2   2   3   7
1   6   3   2   2   3
55  1   3   2   3   0
49  4   5   2   1   0
47  5   7   2   2   6
14  2   9   2   7   7
71  8   9   2   8   8
21  1   2   3   8   9
74  9   2   3   1   6
2   5   3   3   0   8
22  9   3   3   1   0
4   4   6   3   7   9
42  2   6   3   5   4
.. ..  ..  ..  ..  ..
34  2   4   7   6   4
87  0   5   7   8   2
91  1   6   7   3   5
51  6   7   7   7   3
38  5   8   7   2   4
73  4   8   7   6   6
19  1   0   8   9   4
37  3   0   8   5   4
82  4   0   8   2   4
23  7   3   8   0   9
57  7   5   8   9   8
6   5   6   8   1   4
43  2   6   8   8   8
62  0   6   8   0   2
13  7   7   8   4   2
41  5   7   8   8   2
58  5   8   8   2   3
98  4   8   8   7   3
92  6   9   8   0   1
59  6   0   9   8   4
30  5   3   9   6   7
5   2   5   9   4   6
15  0   6   9   8   6
75  7   6   9   2   3
96  3   6   9   8   5
65  4   7   9   7   6
80  3   7   9   6   7
83  3   8   9   9   0
99  5   8   9   3   3
63  2   9   9   0   2

[100 rows x 5 columns]

### Linear Regression

In [52]:
# Obtaining one column from a pandas dataframe
# Returns a series
df['x1']

0     9
1     3
2     3
3     7
4     6
5     5
6     6
7     9
8     3
9     2
10    9
11    3
12    6
13    7
14    9
15    6
16    9
17    3
18    4
19    0
20    5
21    2
22    3
23    3
24    8
25    0
26    5
27    9
28    3
29    5
     ..
70    9
71    9
72    0
73    8
74    2
75    6
76    1
77    3
78    2
79    5
80    7
81    9
82    0
83    8
84    2
85    2
86    1
87    5
88    7
89    5
90    9
91    6
92    9
93    2
94    5
95    4
96    6
97    6
98    8
99    8
Name: x1, Length: 100, dtype: int64

In [53]:
# If you use pop, this DELETES THE COLUMN FROM YOUR DATAFRAME IN PLACE!
df.pop('x1')

0     9
1     3
2     3
3     7
4     6
5     5
6     6
7     9
8     3
9     2
10    9
11    3
12    6
13    7
14    9
15    6
16    9
17    3
18    4
19    0
20    5
21    2
22    3
23    3
24    8
25    0
26    5
27    9
28    3
29    5
     ..
70    9
71    9
72    0
73    8
74    2
75    6
76    1
77    3
78    2
79    5
80    7
81    9
82    0
83    8
84    2
85    2
86    1
87    5
88    7
89    5
90    9
91    6
92    9
93    2
94    5
95    4
96    6
97    6
98    8
99    8
Name: x1, Length: 100, dtype: int64

In [54]:
df

y  x2  x3  x4
0   6   5   5   8
1   6   2   2   3
2   5   3   0   8
3   4   3   3   6
4   4   3   7   9
5   2   9   4   6
6   5   8   1   4
7   1   4   0   7
8   5   5   4   1
9   3   4   8   1
10  5   6   3   0
11  6   0   6   6
12  9   5   2   8
13  7   8   4   2
14  2   2   7   7
15  0   9   8   6
16  8   6   1   9
17  4   0   5   6
18  3   0   5   7
19  1   8   9   4
20  8   4   2   0
21  1   3   8   9
22  9   3   1   0
23  7   8   0   9
24  0   0   7   3
25  3   7   8   4
26  5   6   1   9
27  5   0   5   4
28  0   4   6   4
29  7   4   2   8
.. ..  ..  ..  ..
70  7   4   1   6
71  8   2   8   8
72  9   4   5   6
73  4   7   6   6
74  9   3   1   6
75  7   9   2   3
76  4   4   8   7
77  5   6   4   3
78  7   5   9   8
79  0   0   4   4
80  3   9   6   7
81  7   0   2   9
82  4   8   2   4
83  3   9   9   0
84  3   0   5   1
85  2   1   6   3
86  1   2   2   6
87  0   7   8   2
88  1   3   3   0
89  1   1   8   7
90  2   6   4   5
91  1   7   3   5
92  6   8   0   1
93  3   2   3   7
94  5   0   0   9
95  0   1   3   3
96  3   9   8   5
97  5   1   3   5
98  4   8   7   3
99  5   9   3   3

[100 rows x 4 columns]

:(

In [55]:
# So, make a copy first!
df = pd.DataFrame(np.random.randint(10, size = (100, 5)), columns=['y', 'x1', 'x2', 'x3', 'x4'])
df_copy = df.copy()

In [56]:
df_copy.pop('x1')

0     7
1     3
2     4
3     1
4     7
5     6
6     0
7     1
8     5
9     1
10    8
11    8
12    4
13    0
14    7
15    6
16    8
17    9
18    6
19    6
20    1
21    5
22    9
23    3
24    2
25    9
26    9
27    7
28    2
29    6
     ..
70    4
71    5
72    6
73    9
74    7
75    6
76    5
77    5
78    5
79    8
80    9
81    0
82    4
83    0
84    1
85    8
86    2
87    2
88    1
89    3
90    5
91    8
92    1
93    1
94    4
95    5
96    9
97    4
98    1
99    6
Name: x1, Length: 100, dtype: int64

In [57]:
df_copy.head()

y  x2  x3  x4
0  0   2   3   9
1  4   9   2   4
2  4   8   1   9
3  6   0   6   3
4  5   0   5   1

In [58]:
df.head()

y  x1  x2  x3  x4
0  0   7   2   3   9
1  4   3   9   2   4
2  4   4   8   1   9
3  6   1   0   6   3
4  5   7   0   5   1

In [59]:
# Turn dataframe or series into a numpy array
df.values

array([[0, 7, 2, 3, 9],
       [4, 3, 9, 2, 4],
       [4, 4, 8, 1, 9],
       [6, 1, 0, 6, 3],
       [5, 7, 0, 5, 1],
       [5, 6, 2, 5, 4],
       [2, 0, 3, 7, 7],
       [5, 1, 2, 8, 6],
       [5, 5, 5, 4, 1],
       [2, 1, 1, 3, 7],
       [4, 8, 4, 9, 4],
       [9, 8, 9, 6, 7],
       [9, 4, 6, 5, 0],
       [6, 0, 5, 3, 6],
       [3, 7, 6, 8, 5],
       [3, 6, 2, 6, 1],
       [5, 8, 1, 3, 0],
       [5, 9, 3, 1, 4],
       [4, 6, 8, 4, 7],
       [4, 6, 0, 3, 5],
       [6, 1, 3, 8, 2],
       [7, 5, 6, 2, 7],
       [6, 9, 3, 2, 7],
       [5, 3, 3, 6, 6],
       [5, 2, 1, 4, 4],
       [6, 9, 7, 1, 6],
       [0, 9, 2, 8, 8],
       [4, 7, 5, 3, 3],
       [3, 2, 3, 9, 2],
       [3, 6, 6, 6, 2],
       [2, 4, 6, 1, 8],
       [1, 9, 9, 0, 3],
       [6, 7, 5, 7, 0],
       [5, 0, 6, 2, 0],
       [7, 6, 7, 3, 9],
       [1, 9, 3, 4, 6],
       [2, 3, 2, 2, 3],
       [6, 0, 1, 2, 7],
       [0, 0, 3, 1, 2],
       [6, 4, 0, 7, 4],
       [1, 9, 8, 0, 1],
       [5, 0, 8,

In [60]:
# Turn dataframe or series into a numpy array
df['x1'].values

array([7, 3, 4, 1, 7, 6, 0, 1, 5, 1, 8, 8, 4, 0, 7, 6, 8, 9, 6, 6, 1, 5, 9,
       3, 2, 9, 9, 7, 2, 6, 4, 9, 7, 0, 6, 9, 3, 0, 0, 4, 9, 0, 5, 8, 1, 1,
       7, 4, 2, 5, 2, 9, 6, 7, 1, 0, 7, 2, 0, 8, 0, 3, 4, 5, 7, 1, 0, 2, 8,
       2, 4, 5, 6, 9, 7, 6, 5, 5, 5, 8, 9, 0, 4, 0, 1, 8, 2, 2, 1, 3, 5, 8,
       1, 1, 4, 5, 9, 4, 1, 6])

In [61]:
# not inplace unless inplace=True
new_df = df.drop('y', axis=1)

Okay... that's nice... but why?

Linear Regression

In [62]:
from sklearn.linear_model import LinearRegression

In [63]:
df.head()

y  x1  x2  x3  x4
0  0   7   2   3   9
1  4   3   9   2   4
2  4   4   8   1   9
3  6   1   0   6   3
4  5   7   0   5   1

In [64]:
y = df['y']
X = df.drop('y', axis=1)

In [65]:
lin_model = LinearRegression()

In [66]:
# Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [67]:
lin_model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [68]:
y_predict = lin_model.predict(X_test)

In [69]:
lin_model.coef_

array([ 0.11174453, -0.06342528, -0.02949896,  0.19321905])

In [70]:
lin_model.score(X_test, y_test)

-0.16804720108647575

In [71]:
# can get scoring metrics using sklearn.metrics
from sklearn.metrics import r2_score, mean_squared_error

In [72]:
r2_score(y_test, y_predict)

-0.16804720108647575

In [73]:
mean_squared_error(y_test, y_predict)

8.9147958047366664

matrix multiplication and dot products with numpy

In [74]:
arr1 = np.random.randint(50, size = (1, 10))
arr2 = np.random.randint(50, size = (1, 10))

In [75]:
# won't work, .dot is matrix multiplicatoin and needs appropriate dimensions!
arr1.dot(arr2)

ValueError: shapes (1,10) and (1,10) not aligned: 10 (dim 1) != 1 (dim 0)

In [76]:
arr1.dot(arr2.T)

array([[3964]])

In [77]:
mat1 = np.random.randint(50, size = (5, 2))
mat2 = np.random.randint(50, size = (2, 10))

In [78]:
mat1.dot(mat2)

array([[ 632,  860,  218, 1984, 1772,  496,  832, 1958,  532,  502],
       [1721, 1017,  284, 2873, 2352, 1163,  937, 2714, 1520,  926],
       [1973, 1065,  302, 3101, 2508, 1319,  973, 2912, 1748, 1028],
       [1050,  906,  240, 2298, 1968,  750,  858, 2220,  912,  660],
       [ 707,  723,  188, 1763, 1536,  521,  691, 1718,  608,  482]])