# Python tips to HELP YOU

In [1]:
import numpy as np

In [3]:
foo = np.random.randint(30, size=(20))
print foo
print
print foo.shape

[ 1  1 26 26 27 17 12 23  2  6 23 21 24 23 16 27  9  5  2  5]

(20,)


### Boolean indexing

how about indexing a NUMPY ARRAY with a NUMPY ARRAY OF BOOLEANS

In [4]:
foo

array([ 1,  1, 26, 26, 27, 17, 12, 23,  2,  6, 23, 21, 24, 23, 16, 27,  9,
        5,  2,  5])

In [5]:
foo > 15

array([False, False,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False], dtype=bool)

In [6]:
bool_mask = foo > 15

Get the values from `foo` that are greater than 15

In [7]:
foo[ bool_mask ]

array([26, 26, 27, 17, 23, 23, 21, 24, 23, 16, 27])

You can use this mask on any ol' array of the same size

In [8]:
labels = np.random.choice(['hat', 'whale', 'trebuchet', 'burt'], size=len(foo))
print labels
print labels.shape

['burt' 'burt' 'burt' 'hat' 'trebuchet' 'trebuchet' 'burt' 'hat' 'burt'
 'trebuchet' 'hat' 'whale' 'whale' 'trebuchet' 'hat' 'hat' 'hat' 'hat'
 'hat' 'burt']
(20,)


In [9]:
labels[ bool_mask ]

array(['burt', 'hat', 'trebuchet', 'trebuchet', 'hat', 'hat', 'whale',
       'whale', 'trebuchet', 'hat', 'hat'], 
      dtype='|S9')

### 2D arrays

Syntax: `[row_slice, column_slice]`

In [10]:
bar = np.random.randint(100, size=(8, 6))
print bar
print 'Shape:', bar.shape

[[30 46 45 38 80 89]
 [94 34 35 60 89 32]
 [55 31  1 20 43  0]
 [ 8 26 22 62 45 53]
 [ 4 46 54 20 35 31]
 [23 85 73 38 76 88]
 [20 90 90 95  2 25]
 [51 28 43 27 18 39]]
Shape: (8, 6)


In [15]:
bar[2]

array([55, 31,  1, 20, 43,  0])

In [16]:
bar[3,4]

45

In [17]:
bar[2:5,:-2]

array([[55, 31,  1, 20],
       [ 8, 26, 22, 62],
       [ 4, 46, 54, 20]])

In [18]:
bar[-1:2:-1]

array([[51, 28, 43, 27, 18, 39],
       [20, 90, 90, 95,  2, 25],
       [23, 85, 73, 38, 76, 88],
       [ 4, 46, 54, 20, 35, 31],
       [ 8, 26, 22, 62, 45, 53]])

In [19]:
bar[2,::2]

array([55,  1, 43])

In [20]:
bar[-1]

array([51, 28, 43, 27, 18, 39])

In [21]:
bar[-1:2:-1]

array([[51, 28, 43, 27, 18, 39],
       [20, 90, 90, 95,  2, 25],
       [23, 85, 73, 38, 76, 88],
       [ 4, 46, 54, 20, 35, 31],
       [ 8, 26, 22, 62, 45, 53]])

### Boolean masks with 2D arrays

In [22]:
bar

array([[30, 46, 45, 38, 80, 89],
       [94, 34, 35, 60, 89, 32],
       [55, 31,  1, 20, 43,  0],
       [ 8, 26, 22, 62, 45, 53],
       [ 4, 46, 54, 20, 35, 31],
       [23, 85, 73, 38, 76, 88],
       [20, 90, 90, 95,  2, 25],
       [51, 28, 43, 27, 18, 39]])

In [26]:
bar > 20

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False, False,  True, False],
       [False,  True,  True,  True,  True,  True],
       [False,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True, False,  True],
       [ True,  True,  True,  True, False,  True]], dtype=bool)

In [31]:
(bar > 20).mean()

0.8125

In [32]:
(bar > 20).mean(axis=0)

array([ 0.625,  1.   ,  0.875,  0.75 ,  0.75 ,  0.875])

In [33]:
(bar > 20).mean(axis=1)

array([ 1.        ,  1.        ,  0.5       ,  0.83333333,  0.66666667,
        1.        ,  0.66666667,  0.83333333])

In [24]:
bar[ bar > 20 ]

array([30, 46, 45, 38, 80, 89, 94, 34, 35, 60, 89, 32, 55, 31, 43, 26, 22,
       62, 45, 53, 46, 54, 35, 31, 23, 85, 73, 38, 76, 88, 90, 90, 95, 25,
       51, 28, 43, 27, 39])

Hm, that's just an array of the values greater than 20. What if I want the ROWS where the FOURTH COLUMN is greater than 40?

In [25]:
bar[:, 3] > 40

array([False,  True, False,  True, False, False,  True, False], dtype=bool)

In [35]:
bar

array([[30, 46, 45, 38, 80, 89],
       [94, 34, 35, 60, 89, 32],
       [55, 31,  1, 20, 43,  0],
       [ 8, 26, 22, 62, 45, 53],
       [ 4, 46, 54, 20, 35, 31],
       [23, 85, 73, 38, 76, 88],
       [20, 90, 90, 95,  2, 25],
       [51, 28, 43, 27, 18, 39]])

In [34]:
bar[bar[:, 3] > 40]

array([[94, 34, 35, 60, 89, 32],
       [ 8, 26, 22, 62, 45, 53],
       [20, 90, 90, 95,  2, 25]])

In [40]:
mask3 = bar[3, :] > 40
mask3

array([False, False, False,  True,  True,  True], dtype=bool)

In [42]:
bar[:,mask3]

array([[38, 80, 89],
       [60, 89, 32],
       [20, 43,  0],
       [62, 45, 53],
       [20, 35, 31],
       [38, 76, 88],
       [95,  2, 25],
       [27, 18, 39]])

How about the rows that contain at least one value greater than 70?

In [45]:
mask1 = (bar > 70)
mask1

array([[False, False, False, False,  True,  True],
       [ True, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True, False,  True,  True],
       [False,  True,  True,  True, False, False],
       [False, False, False, False, False, False]], dtype=bool)

In [46]:
mask1.any?

In [47]:
np.any?

In [48]:
mask1.any(axis=0)

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [49]:
mask1.any(axis=1)

array([ True,  True, False, False, False,  True,  True, False], dtype=bool)

In [50]:
bar[mask1.any(axis=1)]

array([[30, 46, 45, 38, 80, 89],
       [94, 34, 35, 60, 89, 32],
       [23, 85, 73, 38, 76, 88],
       [20, 90, 90, 95,  2, 25]])

In [51]:
mask1.all?

### Indexing an array with a list

In [52]:
foo

array([ 1,  1, 26, 26, 27, 17, 12, 23,  2,  6, 23, 21, 24, 23, 16, 27,  9,
        5,  2,  5])

In [53]:
list_mask1 = [1, 6, 4, 2]

In [54]:
foo[list_mask1]

array([ 1, 12, 27, 26])

In [55]:
list_mask2 = [4, 4, 4, 4]

In [56]:
foo[list_mask2]

array([27, 27, 27, 27])

In [57]:
bar[list_mask1]

array([[94, 34, 35, 60, 89, 32],
       [20, 90, 90, 95,  2, 25],
       [ 4, 46, 54, 20, 35, 31],
       [55, 31,  1, 20, 43,  0]])

In [61]:
bar[list_mask2]

array([[ 4, 46, 54, 20, 35, 31],
       [ 4, 46, 54, 20, 35, 31],
       [ 4, 46, 54, 20, 35, 31],
       [ 4, 46, 54, 20, 35, 31]])

In [59]:
bar[:,list_mask2]

array([[80, 80, 80, 80],
       [89, 89, 89, 89],
       [43, 43, 43, 43],
       [45, 45, 45, 45],
       [35, 35, 35, 35],
       [76, 76, 76, 76],
       [ 2,  2,  2,  2],
       [18, 18, 18, 18]])

### Smushing arrays together

In [62]:
x1 = np.random.randint(1240,8754,size=(20,1))
x2 = np.random.random(size=(20,1))

In [63]:
x1

array([[4591],
       [1947],
       [8539],
       [4079],
       [6556],
       [7433],
       [6656],
       [3880],
       [5357],
       [2642],
       [4133],
       [5853],
       [6604],
       [5355],
       [1692],
       [2606],
       [8209],
       [8226],
       [5213],
       [4923]])

In [64]:
x2

array([[ 0.32339631],
       [ 0.21005285],
       [ 0.7821036 ],
       [ 0.97322313],
       [ 0.96936292],
       [ 0.21505212],
       [ 0.53885209],
       [ 0.05462653],
       [ 0.7294111 ],
       [ 0.71657968],
       [ 0.03677606],
       [ 0.76252598],
       [ 0.41105787],
       [ 0.17671987],
       [ 0.77004686],
       [ 0.93933239],
       [ 0.237368  ],
       [ 0.97582596],
       [ 0.71436051],
       [ 0.81225915]])

In [69]:
np.concatenate((x1, x2), axis=1)

array([[  4.59100000e+03,   3.23396310e-01],
       [  1.94700000e+03,   2.10052847e-01],
       [  8.53900000e+03,   7.82103597e-01],
       [  4.07900000e+03,   9.73223126e-01],
       [  6.55600000e+03,   9.69362916e-01],
       [  7.43300000e+03,   2.15052120e-01],
       [  6.65600000e+03,   5.38852091e-01],
       [  3.88000000e+03,   5.46265326e-02],
       [  5.35700000e+03,   7.29411097e-01],
       [  2.64200000e+03,   7.16579681e-01],
       [  4.13300000e+03,   3.67760635e-02],
       [  5.85300000e+03,   7.62525984e-01],
       [  6.60400000e+03,   4.11057866e-01],
       [  5.35500000e+03,   1.76719872e-01],
       [  1.69200000e+03,   7.70046857e-01],
       [  2.60600000e+03,   9.39332389e-01],
       [  8.20900000e+03,   2.37368005e-01],
       [  8.22600000e+03,   9.75825957e-01],
       [  5.21300000e+03,   7.14360510e-01],
       [  4.92300000e+03,   8.12259147e-01]])

In [70]:
np.concatenate((x1, x2), axis=0)

array([[  4.59100000e+03],
       [  1.94700000e+03],
       [  8.53900000e+03],
       [  4.07900000e+03],
       [  6.55600000e+03],
       [  7.43300000e+03],
       [  6.65600000e+03],
       [  3.88000000e+03],
       [  5.35700000e+03],
       [  2.64200000e+03],
       [  4.13300000e+03],
       [  5.85300000e+03],
       [  6.60400000e+03],
       [  5.35500000e+03],
       [  1.69200000e+03],
       [  2.60600000e+03],
       [  8.20900000e+03],
       [  8.22600000e+03],
       [  5.21300000e+03],
       [  4.92300000e+03],
       [  3.23396310e-01],
       [  2.10052847e-01],
       [  7.82103597e-01],
       [  9.73223126e-01],
       [  9.69362916e-01],
       [  2.15052120e-01],
       [  5.38852091e-01],
       [  5.46265326e-02],
       [  7.29411097e-01],
       [  7.16579681e-01],
       [  3.67760635e-02],
       [  7.62525984e-01],
       [  4.11057866e-01],
       [  1.76719872e-01],
       [  7.70046857e-01],
       [  9.39332389e-01],
       [  2.37368005e-01],
 

In [73]:
np.hstack((x1, x2))


array([[  4.59100000e+03,   3.23396310e-01],
       [  1.94700000e+03,   2.10052847e-01],
       [  8.53900000e+03,   7.82103597e-01],
       [  4.07900000e+03,   9.73223126e-01],
       [  6.55600000e+03,   9.69362916e-01],
       [  7.43300000e+03,   2.15052120e-01],
       [  6.65600000e+03,   5.38852091e-01],
       [  3.88000000e+03,   5.46265326e-02],
       [  5.35700000e+03,   7.29411097e-01],
       [  2.64200000e+03,   7.16579681e-01],
       [  4.13300000e+03,   3.67760635e-02],
       [  5.85300000e+03,   7.62525984e-01],
       [  6.60400000e+03,   4.11057866e-01],
       [  5.35500000e+03,   1.76719872e-01],
       [  1.69200000e+03,   7.70046857e-01],
       [  2.60600000e+03,   9.39332389e-01],
       [  8.20900000e+03,   2.37368005e-01],
       [  8.22600000e+03,   9.75825957e-01],
       [  5.21300000e+03,   7.14360510e-01],
       [  4.92300000e+03,   8.12259147e-01]])

In [74]:
np.vstack((x1, x2))

array([[  4.59100000e+03],
       [  1.94700000e+03],
       [  8.53900000e+03],
       [  4.07900000e+03],
       [  6.55600000e+03],
       [  7.43300000e+03],
       [  6.65600000e+03],
       [  3.88000000e+03],
       [  5.35700000e+03],
       [  2.64200000e+03],
       [  4.13300000e+03],
       [  5.85300000e+03],
       [  6.60400000e+03],
       [  5.35500000e+03],
       [  1.69200000e+03],
       [  2.60600000e+03],
       [  8.20900000e+03],
       [  8.22600000e+03],
       [  5.21300000e+03],
       [  4.92300000e+03],
       [  3.23396310e-01],
       [  2.10052847e-01],
       [  7.82103597e-01],
       [  9.73223126e-01],
       [  9.69362916e-01],
       [  2.15052120e-01],
       [  5.38852091e-01],
       [  5.46265326e-02],
       [  7.29411097e-01],
       [  7.16579681e-01],
       [  3.67760635e-02],
       [  7.62525984e-01],
       [  4.11057866e-01],
       [  1.76719872e-01],
       [  7.70046857e-01],
       [  9.39332389e-01],
       [  2.37368005e-01],
 

In [ ]:
np.hstack((x1, x2))

In [76]:
x3 = np.random.randint(-50, -2, size=20)
x3

array([ -3, -35, -30, -42, -28, -20, -49, -17, -19, -25, -48,  -6, -15,
       -33, -48,  -4, -11,  -3, -26, -16])

In [77]:
x3.shape

(20,)

In [78]:
np.hstack((x1, x2, x3))

ValueError: all the input arrays must have same number of dimensions

In [89]:
np.hstack((x1, x2, x3.reshape(-1,1)))

array([[  4.59100000e+03,   3.23396310e-01,  -3.00000000e+00],
       [  1.94700000e+03,   2.10052847e-01,  -3.50000000e+01],
       [  8.53900000e+03,   7.82103597e-01,  -3.00000000e+01],
       [  4.07900000e+03,   9.73223126e-01,  -4.20000000e+01],
       [  6.55600000e+03,   9.69362916e-01,  -2.80000000e+01],
       [  7.43300000e+03,   2.15052120e-01,  -2.00000000e+01],
       [  6.65600000e+03,   5.38852091e-01,  -4.90000000e+01],
       [  3.88000000e+03,   5.46265326e-02,  -1.70000000e+01],
       [  5.35700000e+03,   7.29411097e-01,  -1.90000000e+01],
       [  2.64200000e+03,   7.16579681e-01,  -2.50000000e+01],
       [  4.13300000e+03,   3.67760635e-02,  -4.80000000e+01],
       [  5.85300000e+03,   7.62525984e-01,  -6.00000000e+00],
       [  6.60400000e+03,   4.11057866e-01,  -1.50000000e+01],
       [  5.35500000e+03,   1.76719872e-01,  -3.30000000e+01],
       [  1.69200000e+03,   7.70046857e-01,  -4.80000000e+01],
       [  2.60600000e+03,   9.39332389e-01,  -4.0000000

In [81]:
x3

array([ -3, -35, -30, -42, -28, -20, -49, -17, -19, -25, -48,  -6, -15,
       -33, -48,  -4, -11,  -3, -26, -16])

In [82]:
x3.reshape(-1,1)

array([[ -3],
       [-35],
       [-30],
       [-42],
       [-28],
       [-20],
       [-49],
       [-17],
       [-19],
       [-25],
       [-48],
       [ -6],
       [-15],
       [-33],
       [-48],
       [ -4],
       [-11],
       [ -3],
       [-26],
       [-16]])

In [88]:
bar.reshape(-1,1)

array([[30],
       [46],
       [45],
       [38],
       [80],
       [89],
       [94],
       [34],
       [35],
       [60],
       [89],
       [32],
       [55],
       [31],
       [ 1],
       [20],
       [43],
       [ 0],
       [ 8],
       [26],
       [22],
       [62],
       [45],
       [53],
       [ 4],
       [46],
       [54],
       [20],
       [35],
       [31],
       [23],
       [85],
       [73],
       [38],
       [76],
       [88],
       [20],
       [90],
       [90],
       [95],
       [ 2],
       [25],
       [51],
       [28],
       [43],
       [27],
       [18],
       [39]])

### True is 1, False is 0

In [90]:
bar > 50

array([[False, False, False, False,  True,  True],
       [ True, False, False,  True,  True, False],
       [ True, False, False, False, False, False],
       [False, False, False,  True, False,  True],
       [False, False,  True, False, False, False],
       [False,  True,  True, False,  True,  True],
       [False,  True,  True,  True, False, False],
       [ True, False, False, False, False, False]], dtype=bool)

In [91]:
type(_)

numpy.ndarray

In [92]:
(bar > 50).sum()

17

In [93]:
(bar > 50).mean()

0.35416666666666669

### Oh the booleanity!

In [94]:
bool(5)

True

In [95]:
bool(0)

False

In [96]:
bool('banananas')

True

In [97]:
bool('')

False

In [98]:
bool(None)

False

In [99]:
True == bool(6)

True

In [100]:
False == None

False

In [101]:
0 == False

True

In [102]:
bool(np.nan)

True

In [104]:
np.nan == True

False

In [105]:
np.nan == np.nan

False

In [106]:
bool(np.inf)

True

In [107]:
np.inf == np.inf

True

In [108]:
bool([3, '', 32])

True

In [109]:
bool([])

False

In [110]:
bool([''])

True

In [111]:
None == None

True

In [113]:
np.bool_

numpy.bool_